new PCB
lumapu/ahoy pull request #573
Opened 2023-01-10 08:21 UTC by ManfredBrauchle

I have designed a board which can be equipped with Wemos mini D1 (ESP8266) or mini32 (ESP32), additionally there is a pin header for an OLED . On the backside there is space for the RF module.

2023-01-10 08:45 UTC, knickohr commented
Sehr schönes PCB 👍 So mag ich das 😊

Vor allen werden die unterschiedlichen OLEDs PCBs berücksichtigt !

3 kleine Anmerkungen bezüglich der Kondensatoren habe ich allerdings. Bitte auch an die Versorgungspins direkt am Pinheader der OLEDs Kondensatoren vorsehen. Die OLEDs können schon mal Strom ziehen.

Eine weitere Kondensatorenbatterie würde ich an den 5V Pin des ESP vorsehen, auch wenn wir da keine Spannung/Strom ziehen. Das stabilisiert nochmal.

Und zu guter Letzt vielleicht auch noch einen Schichtkondensator zusätzlich mit aufnehme. So im 100nF Bereich um hochfrequente Schwingungen zu unterbinden.

2023-01-10 08:48 UTC, knickohr requested changes
Siehe Post vorher.

2023-01-10 09:14 UTC, ManfredBrauchle commented
Danke fürs Drüberschauen und deine Kommentare - im Prinzip geb ich dir Recht … 

- aber nachdem die Pinbelegung der OLEDs nicht fix ist wird es schwierig direkt am Pinheader einen C unterzubringen. Auch hatte ich noch nie Probleme mit dem Stromverbrauch von OLEDs (und der Pfad zum vorhandenen C ist recht kurz).
- Der 5V 'Ausgang' am D1 fliegt einem gerne mal um die Ohren - da lass ich die Finger weg, intern hat der 1µ für den 3V3 Regler, das reicht. Am mini32 sind es intern 1µ und 10 µ reichen auch   **IMHO** 
- Entkoppel-Cs halte ich für übertrieben da das ja alles Baugruppen sind die eigene Cs an den Eingangpins haben.
- Nokia: nein, sind das nicht die aus dem vorigen Millenium? 

nichtdestotrotz schau ich mir das nochmal an, vielleicht einen 10µ an die Jumper zum OLED

2023-01-12 12:38 UTC, Meckiilino commented
@ManfredBrauchle 
Mir gefällt deine Leiterplatte sehr - hatte schon vor eine eigene zu erstellen aber da du so tolle Arbeit geleistet hast werde ich deine nehmen. Vielen Dank :-)

Aber:
Magst du nicht für die Leiterplatte ein eigenes Repository aufmachen welches sich forken lässt?
Dann könnte man über ein Pull request mitarbeiten :-)
Oder habe ich irgendetwas übersehen - ich nutze Github nicht so intensiv um mich wirklich auszukennen.

2023-01-12 13:22 UTC, ManfredBrauchle commented
das kann ich machen  - ich bin in Git(hub) auch nicht wirklich fit … aber kriegen wir glaub hin 
ich baue die Platine gerade noch ein **bisschen** um - wird etwas größer (Kreditkartenformat) dann ist mehr Platz und die Funkmodule haben mehr Freiraum … also lohnt es sich evtl. noch drauf zu warten … Screenshot demnächst im discord (https://discord.com/channels/984173303147155506/1060347063281401876)

2023-01-12 14:19 UTC, Meckiilino commented
Leider kommt die Info mit dem Warten ein bisschen zu spät. Ich habe kurz (ca. 30 min) vorher in China bestellt.
Schaden ist gering - 12,00$ (11,66€) komplett mit Versand, Zoll und allem. Da kann man nicht meckern :-)

Mein Versuch von heute Morgen gibt es hier:
https://github.com/Meckiilino/Hoymiles_AhoyDTU_PCB
Die Leiterplatte ist aber nur darauf getrimmt möglichst kompakt zu bleiben - also auch ohne Display usw.
Die Idee mit dem Tantal (statt Elektrolyten) gefällt mir sehr gut - das werde ich bei mir noch ändern...

2023-01-13 18:09 UTC, teletapi commented
Kann man die Platine irgendwo ordern... bzw wann etwa.?

2023-01-13 19:24 UTC, Meckiilino commented
@teletapi 
Du musst dir aus den Dateien von @ManfredBrauchle  GerberDaten erzeugen.
(Projekt öffnen / im Leiterplatteneditor auf Datei - >Plotten gehen / oben das Ausgabeverzeichnis setzen dann
1) unten auf plotten
2) Bohrdaten erzeugen (Ich aktiviere immer "PTH und NPTH vereinen im Bereich excellon"

Dann suchst du die einen Leiterplattenfertiger (darf man den hier nennen ohne Ärger zu bekommen)

2023-01-16 09:37 UTC, closed without merging