Raspberry Pi pyRF24 build instructions from mslookup
lumapu/ahoy pull request #76
Opened 2022-06-16 09:49 UTC by stefan123t

* added Raspberry Pi pyRF24 build instructions from mslookup 
* added DEBUG_FLAGs to config.h of esp8266
* added links to some documentation on the README.md

2022-06-16 21:03 UTC, lumapu requested changes
finde die Idee an sich nicht schlecht, nur mag ich überhaupt nicht den ganzen Code mit `#ifdefs` zu übersähen. 
Wäre es nicht besser statt `DPTRINTLN` ein `DEBUGPRINTLN` einzuführen und das `#ifdef` dann in die `debug.h` auszulagern?

2022-06-16 21:42 UTC, stefan123t commented
@lumapu, ja `#ifdefs` pflastern meinen weg =^/ 
Ich bin auch noch nicht zufrieden damit, irgendeine #ifdef Funktion der man das Debug Modul übergeben kann wäre super.
Ich kann mich gerne nochmal umsehen, vielleicht kann man ja auch was pragmatisches und generisches mit `#pragma` machen ?

2022-06-16 22:22 UTC, merged

2022-06-16 22:24 UTC, lumapu commented
@stefan123t was hälst du von einer gestaffelten Debug-Ausgabe, dann könnte man die letzten Änderungen alle in Verbose schieben und je nach compile sich verschiedene Meldungen anzeigen lassen, default wäre dann `DBG_INFO`

```
#define DBG_ERROR       1
#define DBG_WARN        2
#define DBG_INFO        3
#define DBG_DEBUG       4
#define DBG_VERBOSE     5

#define DEBUG_LEVEL DBG_INFO

#if DEBUG_LEVEL >= DBG_ERROR
    #define PERR(str) printf("E: %s\n", str);
#else
    #define PERR(str)
#endif
    
#if DEBUG_LEVEL >= DBG_WARN
    #define PWARN(str) printf("W: %s\n", str);
#else
    #define PWARN(str)
#endif
    
#if DEBUG_LEVEL >= DBG_INFO
    #define PINFO(str) printf("I: %s\n", str);
#else
    #define PINFO(str)
#endif
    
#if DEBUG_LEVEL >= DBG_DEBUG
    #define PDBG(str) printf("D: %s\n", str);
#else
    #define PDBG(str)
#endif
    
#if DEBUG_LEVEL >= DBG_VERBOSE
    #define PVERB(str) printf("V: %s\n", str);
#else
    #define PVERB(str)
#endif

#define DPRINTLN(level, str) ({\
    switch(level) {\
        case DBG_ERROR: PERR(str);  break; \
        case DBG_WARN:  PWARN(str); break; \
        case DBG_INFO:  PINFO(str); break; \
        case DBG_DEBUG: PDBG(str);  break; \
        default:        PVERB(str); break; \
    }\
})

```

2022-06-16 22:27 UTC, stefan123t commented
Ups ich glaube die DBGXXX definitionen erwarten keine F("Strings") sondern funktionieren mit printf ( PSTR(""), paramX, paramY) etc.
Das ist noch effektiver als unsere F("String") + paramX + F("String2") Verschachtelungen...
Du hast das bereits gemerged, compiliert das bei Dir überhaupt ?
Ja die Staffelung fände ich auch interessant, weil es doch einige Ausgaben (die z.B. bei jedem Loop nur ein Zeichen ausgeben) gibt, die ich nur im Verbose+Verbose Modus sehen will.

2022-06-16 22:38 UTC, lumapu commented
habs gerade gemerkt und gefixt. Dann stelle ich mal um auf gestaffelte Ausgaben - dann können wir die Level je nach Augenmerk lokal verstellen.

2022-06-21 22:02 UTC, stefan123t commented
Das `{ (void)0; } while (0)` Konstrukt übersetzt der Compiler anscheinend zielsicher in ein `NOP;`