Improved ESP-Restart after MQTT Fail
lumapu/ahoy pull request #86
Opened 2022-07-02 20:15 UTC by Oliver-ger

2022-07-04 20:22 UTC, lumapu commented
Gibt es denn keine andere Möglichkeit als den kompletten ESP neu zu starten? Wir müssen mal ergründen was ein ESP Neustart von einem Reconnect unterscheidet. 
Wie das letzte Mal würde ich den PR erst mal als Workaround für interessierte offen lassen, aber nicht mergen.

2022-07-07 21:15 UTC, stefan123t commented
@Oliver-ger gibt es auch die Option das mqtt PubSubClient Objekt zu destroyen und neu anzulegen, sobald die WiFi Verbindung wieder steht.
Ich vermute dass sich die beiden Dienste (WiFi & MQTT) gegenseitig blockieren könnten ?

2022-07-10 17:47 UTC, Oliver-ger commented
@stefan123t Das muss ich mit anschauen, ob das geht. Eine Wifi Verbindung kann man trennen. Aber MQTT ? Habe gerade ne Uptime > 2 Tage.

2022-07-10 21:50 UTC, stefan123t commented
@Oliver-ger ja die TCP/UDP-Verbindung wird vermutlich für jede MQTT-Nachricht erneut initiiert. Andererseits scheint es ja so eine Art isConnected Method im PubSubClient zu geben. Die Frage ist ja aber in welchem Zustand die MQTT Verbindung des PubSubClient wirklich ist, wenn dem ESP mal die WiFi Verbindung wegbricht. Dann müsste m.E. die MQTT Verbindung bzw. das PubSubClient Objekt destroyed und neu angelegt werden, wie sonst m.W. nur in der Setup Routine.

2022-07-12 07:43 UTC, stefan123t commented
Vielleicht kannst Du die drei Versuche mit dem delay(2000) und dem Restart aus dem Code rauslassen, dann haben wir an der Stelle keine unnötige Vezögerung / weitere loops aber ein verbessertes Error handling. Da er ja sinnigerweise erst die WiFi Verbindung prüft und dann erst die MQTT Verbindung. Das wäre dann doch eine Verbesserung zum Status Quo!

2022-07-18 17:23 UTC, lumapu requested changes
Es wird nur ein Verbindungsversuch gestartet, wenn Benutzername und Passwort gesetzt sind. Es gibt aber auch Installationen ohne Authentifizierung.

2022-07-20 00:12 UTC, stefan123t commented
@lumapu guter Punkt das war mir entgangen dass die beiden Varianten vorher existierten.

2022-08-03 12:43 UTC, stefan123t commented
siehe #106

2022-08-03 13:29 UTC, HorstG-57 commented
ich hätte eine Lösung :

https://github.com/grindylow/ahoy/issues/106#issuecomment-1203944248

2022-08-03 15:05 UTC, Oliver-ger commented
@HorstG-57 Das klingt ja vielversprechend.☺️ Jetzt musst Du Deinen Code veröffentlichen - vielleicht mit einem Pull Request ?

2022-08-03 22:06 UTC, stefan123t commented
@Oliver-ger wir haben aktuell zwei ähnliche Ansätze das Problem ohne Restart des ESP zu lösen.

2022-08-04 06:55 UTC, stefan123t commented
@Oliver-ger vielleicht kannst Du mal die Version 0.4.26 bei Dir ausprobieren und das Issue schließen, falls das Problem damit für Dich behoben ist ?

2022-08-04 08:23 UTC, Oliver-ger commented
@stefan123t Alles klar, ich spiele die Version 0.4.26 gleich heute Abend auf.

2022-08-04 12:25 UTC, lumapu commented
@HorstG-57 wenn ich es in #120 richtig verstanden habe sollte man diesen PR auch mergen

2022-08-04 18:00 UTC, Oliver-ger commented
Mit der Version 0.4.26 baut er jetzt zumindest bei WLAN Ausfall und Wiederkehr sofort die MQTT Verbindung gleich wieder auf. Das war vorher nicht so. 
Jetzt mal sehen wie lange die Uptime ist.

2022-08-05 16:06 UTC, Oliver-ger commented
Also ich habe hier 2 ESP8266 am Start. Der eine mit dem Softwarestand 0.4.20 hat im Morgengrauen neu gebootet wegen MQTT Ausfall. Der zweite mit der neuen Version 0.4.26 ist durchgelaufen. Ich denke das war‘s 😀

2022-08-05 21:10 UTC, stefan123t commented
@Oliver-ger bitte closen. Danke!

2022-08-05 21:22 UTC, lumapu approved these changes

2022-08-05 21:24 UTC, lumapu commented
hab irgendeinen falschen Knopf gedrückt, jetzt steht hier "Changes approved", das wollte ich garnicht.

2022-08-06 07:09 UTC, closed without merging

2022-08-06 07:10 UTC, Oliver-ger commented
Pull Request geschlossen, da erledigt.